Traceback (most recent call last):
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/natalie-widmann/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# von string zu int
value = '5.6'
var = int(value)
print(var)
print(type(var))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[10], line 3[0m
[1;32m      1[0m [38;5;66;03m# von string zu int[39;00m
[1;32m      2[0m value [38;5;241m=[39m [38;5;124m'[39m[38;5;124m5.6[39m[38;5;124m'[39m
[0;32m----> 3[0m var [38;5;241m=[39m [38;5;28mint[39m(value)
[1;32m      4[0m [38;5;28mprint[39m(var)
[1;32m      5[0m [38;5;28mprint[39m([38;5;28mtype[39m(var))

[0;31mValueError[0m: invalid literal for int() with base 10: '5.6'

